### ISSUE TITLE
在post方法前增加[JsonDataConvert]，如果post提交内容不是合法的json时报错

### ISSUE THREAD

**Issue by hugeng1979** [IKende/FastHttpApi#100]
如果post提交的内容不是合法的json字符串， 比如少了个双引号等
页面返回： status 500 
http execute /ding/message/send error 
Invalid JavaScript property identifier character: ". Path 'company', line 2, position 8.

这种返回内容，不太友好。最好能返回类似于
new JsonResult(new ActionResult(-1, "提交的不是标准JSON格式，请检查"));

我查看了JsonDataConvertAttribute 代码，应该是在Execute中执行时出现了异常。
我想自己编写一个类继承自JsonDataConvertAttribute
override Execute方法，
try { base.Execute(dataContext, request); }
            catch
            {
但是，发现写不下去了。没法返回内容。因为这个类调用是handler.DataConvert.Execute(request.Data, request);

**Comment by hugeng1979** [comment]
debug后，发现和JsonDataConvertAttribute 类无关。没有执行到这个类就结束了。

**Comment by IKende** [comment]
这种情况一般由用户端判断`http`状态码来处理
