### ISSUE TITLE
growth byte[] in heap. How can I fix it?

### ISSUE THREAD

**Issue by Vladislav93** [IKende/FastHttpApi#103]
Hello!
I see, that byte[] objects growth up in a heap
all this byte array is 8192 size, which equal  "this.BufferSize = 8192;"

show I send a response:
if (e.Request.Session?.Server != null)
{
var rawResult = new RawResult(result); 
e.Response.Result(rawResult);
}
How can i fix this problem?
may be call some dispose or clear some buffer?

**Comment by IKende** [comment]
you can do it 
``` csharp
//RawResult
 public virtual void Write(PipeStream stream, HttpResponse response)
        {
             try
             {
　　　　　　stream.write(rawbytes);
             }
            finally
            {
                //dispose or clear raw bytes
            }
        }
```

**Comment by Vladislav93** [comment]
But may be I do something wrong :)
```
public class RawResult : IResult
    {
        private readonly string _data;
  
      public RawResult(string data)
        {
            _data = data;
            Length = data.Length;
        }

        public string ContentType => "application/json";

        public int Length { get; set; }

        public bool HasBody => true;

        public void Setting(HttpResponse response)
        {
        }

        public void Write(PipeStream stream, HttpResponse response)
        {
            stream.Write(_data);
        }
    }
```

```
 var rawResult = new RawResult(strResult);

e.Response.Result(rawResult);
```

and in a heap, byte[] every obj has value like this:

`"HTTP/1.0 200 OK\r\nServer: BeetleX\r\nContent-Type: application/json\r\nContent-Length: 16\r\n\r\n{"result": "ok"}xUAA8HzJQADwfM1AAPB80UAA8HzVQADwfNlAAPB83UAA8HzhQADwfOVAAOx80IAM8HzQgAzwfNCADGQ8RBBEvNDNRAD0fNFEAPR81UQA9HzZRAD0fN1EAPR84UQA9HzlRADwvNTBRAD0fMVEAPQ8qAz0fNSoDPR81bAkYIGZp0aYPUAAMHzVQADwfNlAAPB83UAA8HzhQADwfOVAAOy82MFAAPB8xUAA8D4wMGFBjYWN0dXweEHK4Fg9ZAA0fM1kARR80WQBFHzVZAEIBvuowYW1wuosD3DQFzeoJWxgBNHwBpusCUyMCpTQBJJAHDBUvODUMFQ5tZGVmYXVsexgQZzF8IyIsCAAAyxgCOJISedlwLyIxTQA0HjUKFQ9NACceNAkVD00AIRY4TQAfNE0ANB41BxUPTQAnHjYGFQ9NACEWOZoAHzdNADQeNgQVD00AIQCZORN5XCMfOU4AKBgyTgAeMwQVD+oAKB4zAxUPTgAoHjcCFQ85ASkeNgIVD08AKR41AhUPTwApHjQCFQ87ASgCTgAPDgMvETVOAB45ARUPTgAoA7/qHzhPADUeMQEVD08AKQJsIw8SAy8YNE8ADxMDLxgzTwAPFAMvGDJPAB8zTwA1HjH8FA9PACkeMPsUD08AKB45+RQPigEpHjD4FA9PACgeOfYUD3YCKR4w9RQPTwApAi4mDxQDNR458hQPEwMpHjGhFA8SByISNk8ADp8UD8MCIgJOAB4ynRQPTgAoHjObFA/WBSgCTgAP1gU1HjKXFA+GASIDhgUO9RMPTgAiA8ACDvMTD04AKB4y8BMPTgAoHjPtEw9OACIXM5wAHzVOADQeM+cTD04AKAKGAQ8iAi8XMbsGHzQJCywFSQAvNTCYADUeMYcTD08AKR4whRMP5wAjHjB9Ew9JACMeMX"`

`"HTTP/1.0 200 OK\r\nServer: BeetleX\r\nContent-Type: application/json\r\nContent-Length: 16\r\n\r\n{"result": "ok"}01\r\n\r\n{"last_transaction_ts": "0", "unused_transactions": {}, "result": "ok", "used_transactions_count": 0}ount": 2}ABq4JD1kAAVA5Mjc1OCsOLTY4UgEwX19D2gofMToABZA4MjU5LjIwMDKFJRJTHRUBMgAgRW4vQh9jMAEC3DgwMjAxNTE4LjEyMDU5AF9Mb2JieTYABoA3NTYuMDAxMskBcUFyZW5hX0OWCw8xAASRMTE0ODguMDI0GB9uUHJhaXJpzgAFLgCBMzM5MC42OTdaAgkuHQ8yAAOhMzgxOTUxLjE5N8cAElRNDwF+Hw8xAANhNTQ1NjU1MQAAYwAQRH4xB3ABDzUABJE1NjgwNC44NznAAhBTQgpvX1BsYXRvmAAFMDYzN1ISWzY4OTgxMgAfMzIAA8s5ODQ4NzMuMTMzNDYyAA/BAgIA7BCCNjQ2MC41NTOEDwfWTgUxAAIhFATcMygxLBYAB8wPljU3NS4xODEyNnYBJWluwFkZIthdEWzXCwEnEQYOAAU1E0JzdGlurxAGshOkNDMwMC4wOTQ2N4QEBW0hCEMAVm9yaWdpOAAAoQJAMjguNWc1BpcAIGR1tFM9MjEyqQACTQUYaSNfAxkAAVxTArMAA2oUBBIAIiJpLAEGzB8DD1oB9xRdc3RpY3M4AAYXAAEVDgWOGAIpAAFbAQFBBQYKAAVTESJtb7cfJ2lzqTUEoxEFDzIyYWtlogEPKwAOAAcLh192Ml9jYXJ03l0RbdVfAScSVHViamVjHFMNSwAuXSwVAAETAAOoDwPGCQdTARBzZgEMEAAJdgFDcG9vbNoSBKcAAm8CABkADH1RBCMABdJKCMQCJywiuAIDtg8IswLANi41Mzc0OCwibGlzvwYP0A`


yes, this is my response :  "{"result": "ok"}" and "{"last_transaction_ts": "0", "unused_transactions": {}, "result": "ok", "used_transactions_count": 0}"

And in the second array, I see, that it's reuse buffer.

But why is it still growing with a stable server load... 

I think maybe try set KeepAlive = false, and it helps just a little bit

**Comment by IKende** [comment]
Pipestream use a common buffer pool,the buffer used in all connections. default max size is 100mb,
Options.BufferPoolMaxMemory property setting.
