### ISSUE TITLE
options问题

### ISSUE THREAD

**Issue by a232910834** [IKende/FastHttpApi#11]
options问题
设置了options的表头后。
接口在无请求状态一段时间后，options貌似失效了。中间过程是1点到4点多中间是无数据请求。空置状态。然后4点多再次请求。提示的是 cors不支持跨域。疑似options失效。很费解。这。。。

**Comment by IKende** [comment]
```
    "WriteLog": true,
    "LogLevel": "Info",
```
配置这两个项看一下日志相关url 有没options

**Comment by a232910834** [comment]
![image](https://user-images.githubusercontent.com/45068950/49122161-39c2b500-f2ee-11e8-9f4e-460019f1aef7.png)

**Comment by IKende** [comment]
这可能是dotnet core的一个bug[https://github.com/dotnet/corefx/issues/33794](https://github.com/dotnet/corefx/issues/33794)

新版已经调整了应用方式，初步解决这一问题

**Comment by IKende** [comment]
fix with 1.0.5.6
