### ISSUE TITLE
今天升级到1.7.98出现异常

### ISSUE THREAD

**Issue by zhusheping** [IKende/FastHttpApi#111]
System.MissingMethodException:“Method not found: 'Void BeetleX.ServerOptions.set_PrivateBufferPool(Boolean)'.”
![image](https://user-images.githubusercontent.com/23443907/75640562-778c5700-5c70-11ea-98db-6b4d68986fed.png)
一路降级1.7.7.5到也不行

**Comment by IKende** [comment]
要把`beetlex`降级，`beetlex`的`buffer`配置修改了一下，不能兼容现有版本的`FastHttpApi`。

**Comment by zhusheping** [comment]
beetlex降级后可以了。
