### ISSUE TITLE
引入Swagger

### ISSUE THREAD

**Issue by gwhzh21** [IKende/FastHttpApi#113]
如果想引入Swagger类似的文档工具，有什么建议？

**Comment by IKende** [comment]
可以单独写个扩展包，依据`HttpApiServer.ActionFactory.Handlers`的信息来生成对应的Swagger的json提供给Swagger js即可，生成Swagger的json有点繁琐。最后可以借助HttpApiServer.Register的方法来引入到服务中，如果实现过程中有困难可以提出。

**Comment by gwhzh21** [comment]
好的，收到。
