### ISSUE TITLE
webapi download  file 问题

### ISSUE THREAD

**Issue by yesyeey** [IKende/FastHttpApi#116]
我想实现webapi下载文件  改写downloadjson   下面的 内容
          const long ChunkSize = 1048576;
            byte[] buffer = new byte[ChunkSize];

            System.IO.FileStream iStream = System.IO.File.OpenRead("3.rar");
            long dataLengthToRead = iStream.Length;

            using (iStream)
            {
                while (dataLengthToRead > 0)
                {
                    int lengthRead = iStream.Read(buffer, 0, Convert.ToInt32(ChunkSize));
                    stream.Write(buffer, 0, lengthRead);
                    dataLengthToRead = dataLengthToRead - lengthRead;
                }
                iStream.Dispose();
                iStream.Close();
            }

文件超过100M 就提示Create buffer error, maximum number of buffer pools!”
这个是由于限制buffer导致的。除了增加maxbuffer外用websocket外，请教下还有其他办法吗。

**Comment by IKende** [comment]
新版本中提供`FileResult``
``` csharp
 return new FileResult(@"/httpd.zip");
```

**Comment by yesyeey** [comment]
完美解决
