### ISSUE TITLE
关于Post Body格式问题

### ISSUE THREAD

**Issue by senioi** [IKende/FastHttpApi#119]
目前使用BeetleX.FastHttpApi.Clients
请问大佬,POST的Body如何保持原文?
尝试过 [NoDataConvert] / [JsonFormater] 都无法达到预期效果.

代码如下:

```
    using (var Web = new Host())
            {
                Web.Crate(dHost1, dHost2);
                var obj = new { hello = "value" };
                await Web.IPostService.testPost(12345, "{\"Updated\":1587412499,\"Name\":\"123456eee\"}");
            }
```

```
     public interface IPostService
     {
         [Post]
         [JsonFormater]
         Task<object> testPost([CQuery]int Ids, string Body);
 }

```
服务器收到的内容是(**多了一组双引号**):

> ""{\"Updated\":1587412499,\"Name\":\"123456eee\"}""

如果不使用 **[JsonFormater]**
服务器收到则是表单

> Body=%7B%22Updated%22%3A1587412499%2C%22Name%22%3A%22123456eee%22%7D

**Comment by IKende** [comment]
你应该post一个对象，而不是一个`string`, `JsonFormater`会对参数进行json处理

**Comment by senioi** [comment]
> 你应该post一个对象，而不是一个`string`, `JsonFormater`会对参数进行json处理

谢谢大佬抽空回复,Body可能是Base64或者binary ,请问能否加个原始post的功能呢?
 比如这样 [Body]

**Comment by IKende** [comment]
可以实现`IBodyFormater`来写入不同的格式
