### ISSUE TITLE
post 路径的问题

### ISSUE THREAD

**Issue by nodyang** [IKende/FastHttpApi#120]
![image](https://user-images.githubusercontent.com/3090191/80609508-bd944a00-8a6a-11ea-83f9-068679c67787.png)
![image](https://user-images.githubusercontent.com/3090191/80609650-efa5ac00-8a6a-11ea-8962-ac7c7df78d07.png)

我明明设置了Post 最后还是按方法名去映射的路径

![image](https://user-images.githubusercontent.com/3090191/80612478-9a6b9980-8a6e-11ea-982b-6148961559dd.png)
我是按这个文档理解的

**Comment by nodyang** [comment]
我用Demo 是么有问题的。但这个问题确实在线上反应出来。就是提示没有路径 然后我用方法名居然OK

**Comment by nodyang** [comment]
![image](https://user-images.githubusercontent.com/3090191/80660535-8a7ba600-8abe-11ea-9741-a6d4e2933e49.png)
![image](https://user-images.githubusercontent.com/3090191/80660561-a41ced80-8abe-11ea-942d-469941ce818c.png)

**Comment by IKende** [comment]
`Route`的属性设置是参数转议用的，直接用于方法重命名我也没有测过。

**Comment by IKende** [comment]
可以查看启动的`rewrite`日志，`Route`只是增加一个`rewrite`.这样就多了一个访问路径，你在`API`上接是不会有`rewrite`的路径的

**Comment by nodyang** [comment]
谢谢哥
