### ISSUE TITLE
突然宕机

### ISSUE THREAD

**Issue by yintao666** [IKende/FastHttpApi#121]
今天突然奇想升级到了最新版本,我不知道是我组件匹配不是不是不对,发布正式之后基本1小时停掉一次API服务(控制台上看起来是正常的,只是之后所有请求都被超时了),导致App用户直接炸裂...我检查了__UnhandledException日志和其他日志,都没发现异常报告,我看控制台连接人数也不多,今天做多的时候请求评率是1200/分钟,之前是好好的,升级之后就容易连接超时...还请大佬给点意见...小弟感激不尽
附上升级的版本信息:
BeetleX.FastHttpApi:   1.8.2.2
BeetleX.FastHttpApi.Admin:  1.1.4
BeetleX.FastHttpApi.Hosting: 1.2.4

**Comment by IKende** [comment]
这个版我已经使用了一段时间，还暂没有碰到这情况；如果你能访问后台监控说明服务是正常动作的。

**Comment by yintao666** [comment]
嗯嗯  好的  我再检查一下是否是我加的filter导致的 蟹蟹
