### ISSUE TITLE
例子中的WebSocket.UploadFiles报错。

### ISSUE THREAD

**Issue by dms-aping** [IKende/FastHttpApi#123]
Core3.1 
FastHttpApi1.8.22
BeetleX 1.5.11
上传文件时报错。
![err](https://user-images.githubusercontent.com/61961235/80896686-9ddb7b00-8d23-11ea-9fdb-f6e2224dad2b.jpg)

**Comment by IKende** [comment]
是不是把`MaxBodyLength`设置过大了，这sample是分块上传，所以无须调整`MaxBodyLength`.
`MaxBodyLength`作用不仅是提交大小限制，ws在输出的时候同样依据这个值作为buffer从pool用获取，所以这值不能设置太大。

**Comment by dms-aping** [comment]
谢谢回复。
MaxBodyLength设置大是因为在测试Web.UploadFiles文件上传的时候，设置之后才能上传大一点的文件。
将MaxBodyLength的设置去掉之后，的确可以上传文件了。但超过4M之后，会经常提示。

Serve端：



确定之后又可以继续上传了。

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Henry"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月3日(星期天) 上午10:30
收件人:&nbsp;"IKende/FastHttpApi"<FastHttpApi@noreply.github.com&gt;;
抄送:&nbsp;"阿平"<zhusp@deepmind.cn&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [IKende/FastHttpApi] 例子中的WebSocket.UploadFiles报错。 (#123)





 
是不是把MaxBodyLength设置过大了，这sample是分块上传，所以无须调整MaxBodyLength.
 MaxBodyLength作用不仅是提交大小限制，ws在输出的时候同样依据这个值作为buffer从pool用获取，所以这值不能设置太大。

**Comment by IKende** [comment]
ws默认是RPS限制`WebSocketMaxRPS`可以设置大些

**Comment by dms-aping** [comment]
WebSocketMaxRPS设置为240.
115M的文件可以上传。但上传速度太慢了，在本机测试这个115M的上传到20花了5分钟，就手动停止测试了？
如何能提速？
如果上传的文件大小为2g，如何设置比较好？
谢谢啦！

**Comment by yswenli** [comment]
可以使用 saea相关的组件试试
https://github.com/yswenli/SAEA/tree/master/Src/SAEA.MVCTest/Controllers
