### ISSUE TITLE
请问 xxxController.js 文件是如何自动生成的？

### ISSUE THREAD

**Issue by mirror222** [IKende/FastHttpApi#125]
我看例子程序中有这个头，看样子应该是自动生成的。

/************************************************************************************
FastHttpApi javascript api Generator Copyright © henryfan 2018 email:henryfan@msn.com
https://github.com/IKende/FastHttpApi
**************************************************************************************/

**Comment by IKende** [comment]
这种方式已经移走了，最新`beetlex.js`使用可以参考
https://github.com/IKende/AdminUI
