### ISSUE TITLE
不想使用VUE，如何实现跟ASPX.NET 一样的模板文件？

### ISSUE THREAD

**Issue by mirror222** [IKende/FastHttpApi#126]
比如我有一个头文件header.html,  footer.html， 已经网页正文的内容Body1.html,Body2.html....
header.html 文件的内容有些内容是动态生成的。

当客户访问 /index.html 的时候， 我需要根据实际情况生成header.html， 然后拼装 Body1.html 及 footer.html

当客户访问 /order.html 的时候， 我需要根据实际情况生成header.html， 然后拼装 Body2.html 及 footer.html

.....
请问能告诉我一下大概的使用方法吗？如果有简单的函数代码就更好了。
谢谢。

**Comment by IKende** [comment]
可以在action返回自定义html的`IResult`然后自己用ajax处理，如果想要服务器模板，那就要自己扩展支持`Razor`的`IResult`

**Comment by mirror222** [comment]
有相关的文档或者例子吗？感谢

**Comment by mirror222** [comment]
谢谢。我学习一下
