### ISSUE TITLE
请问如何自定义server 头？

### ISSUE THREAD

**Issue by mirror222** [IKende/FastHttpApi#128]
在config文件中可以设置吗？

**Comment by IKende** [comment]
暂没有属性提供设置

**Comment by eddyyuen** [comment]
因客户安全要求不能显示有意义的Server头。所以用 openresty 加了这一行
header_filter_by_lua 'ngx.header.server = "UnkownServer"';

**Comment by mirror222** [comment]
你这个是二次代理？

**Comment by eddyyuen** [comment]
> 你这个是二次代理？

用nginx做反向代理

**Comment by asuradoll** [comment]
其实这个需求很多人都有，因为一旦知道了是哪个框架，就有办法针对性的攻击。

**Comment by IKende** [comment]
`v1.8.5`支持`ServerTag`和`OutputServerTag`设置

**Comment by asuradoll** [comment]
太棒了~
