### ISSUE TITLE
如何设置http请求的header呢

### ISSUE THREAD

**Issue by tzm1119** [IKende/FastHttpApi#13]
如何设置http请求的header呢

**Comment by IKende** [comment]
可以在方法中定义IHttpContext参数，通过Request获取，Response设置，大概代码如下:
```
        public string SetHeader(string name, string value, IHttpContext context)
        {
            //get header context.Request.Header["name"];
            context.Response.Header[name] = value;
            return value;
        }
```

**Comment by tzm1119** [comment]
下面这个HttpApiClient发送请求时的Header怎么设置，我要设置 "Bearer", accessToken

HttpApiClient apiClient = new HttpApiClient(GZSetting.GzApiIpAndPort);
 ITestInfo testInfo = apiClient.Create<ITestInfo>();
model.MbList= testInfo.GetMbInfo();

**Comment by IKende** [comment]
可以在方法中定义一个参数，然后加个[CHeaderAttribute]标签，那这个参数就会加到header中。
FastHttpApi的client还没有完善的测试，暂不建议使用。因为后面已经计划用HttpClusterApi来代替它

**Comment by tzm1119** [comment]
下面是我的MVC的Action里要用HttpApiClient调用远程API,我的Header应该在哪里设置？  
public async Task<IActionResult> Index()
        {
            string accessToken = await HttpContext.GetTokenAsync("access_token");
       
            HbAndMbInfoList model = new HbAndMbInfoList();
            HttpApiClient apiClient = new HttpApiClient(GZSetting.GzApiIpAndPort);
            ITestInfo testInfo = apiClient.Create<ITestInfo>();
            model.MbList = testInfo.GetMbInfo();
            model.HbList = testInfo.GetHbInfo();
            return View(model);
        }

**Comment by IKende** [comment]
方法里可以这样定义 GetMbInfo([CHeader] string token)

**Comment by tzm1119** [comment]
方便加个 微信么 我的微信是  tzm19921119

**Comment by IKende** [comment]
可以加一下28304340这个ＱＱ
