### ISSUE TITLE
SetDebug 如何使用？

### ISSUE THREAD

**Issue by mirror222** [IKende/FastHttpApi#130]
1. 官网的帮助文档服务器好像异常了。
2. SetDebug 请问怎么使用？

 services.UseBeetlexHttp(o =>
                   {
                       o.LogToConsole = true;
                       o.ManageApiEnabled = false;
                       o.Port = 80;
                       o.SetDebug（XX?）
                       o.LogLevel = BeetleX.EventArgs.LogType.All;
                       
                       JWTHelper.Init();
                   }

**Comment by IKende** [comment]
`SetDebug`只是用来设置静态文件路径，只在`debug`模式下生效，主要方便开发时候修改静态文件不用编译。
