### ISSUE TITLE
beetlex内存不断在增长？

### ISSUE THREAD

**Issue by dms-aping** [IKende/FastHttpApi#131]
我用FastHttpApi做了个控制台程序，来做自动更新的服务端。有获取版本的http接口和下载文件的接口，运行过几次之后，就发现内存使用飙升。
分别对两次内存的使用做了分析，截图对比如下：
![image](https://user-images.githubusercontent.com/61961235/82637459-67649200-9c37-11ea-990f-a58b72f3e1c2.png)

**Comment by IKende** [comment]
对于`beetlex.buffer`的机制不好解释,默认有个总大小限制的，分配超出后就会就层导致服务拒绝。闲置的buffer也不会马上释放。你运行长时间观察就知道了

**Comment by dms-aping** [comment]
那怎么配置可以释放闲置buffer？不能请求一次，buffer就增长一次。怀疑如果是文件类型返回结果，buffer会增加更多。

**Comment by IKende** [comment]
组件内部会处理这个你不用担心，如果buffer总分配超过默认值100MB则会有异常。
