### ISSUE TITLE
SpanJsonResultFilter 无法使用

### ISSUE THREAD

**Issue by gwhzh21** [IKende/FastHttpApi#133]
虽然用nuget 安装的是BeetleX.FastHttpApi1.8.2.5
但在[BeetleX.FastHttpApi.SpanJson.SpanJsonResultFilter] 这里老是提示要引用FastHttpApi1.4.9.8?
        public List<Employee> EmployeesSpan()
        {
            
            return DataHelper.Defalut.Employees;
        }

**Comment by IKende** [comment]
自行拿 https://github.com/IKende/FastHttpApi/tree/master/Extend/BeetleX.FastHttpApi.SpanJson

**Comment by gwhzh21** [comment]
ok
