### ISSUE TITLE
设置 JsonConvert.DefaultSettings 后接口解析 json 参数错误

### ISSUE THREAD

**Issue by eddyyuen** [IKende/FastHttpApi#137]
**1、设置了全局的日期处理格式：**
JsonSerializerSettings setting = new JsonSerializerSettings();
            JsonConvert.DefaultSettings= new Func<JsonSerializerSettings>(() =>
            {
                //日期类型默认格式化处理
                setting.DateFormatHandling = DateFormatHandling.MicrosoftDateFormat;
                setting.DateFormatString = "yyyy-MM-dd HH:mm:ss";
                setting.NullValueHandling = NullValueHandling.Ignore;
                return setting;
            });

**2、Controller的Post方法**
  [Post]
        [JsonDataConvert]
        public JsonResult Post(string id)
        {
            return new JsonResult(ret);
        }

**3、Post数据  {"id":"test"}  显示：**
http execute /Post error 
/Post bind id parameter error Error reading string. Unexpected token: PropertyName. Path 'id'.

**Comment by IKende** [comment]
服务端是默认JsonSerializerSettings，可能和client定义的无法匹配处理引起反序列化错误

**Comment by IKende** [comment]
突然想起可以实现`DataConvertAttribute`来解决，参考默认实现
``` csharp
    public class JsonDataConvertAttribute : DataConvertAttribute
    {
        public override void Execute(IDataContext dataContext, HttpRequest request)
        {
            if (request.Length > 0)
            {
                using (request.Stream.LockFree())
                {
                    using (System.IO.StreamReader streamReader = new System.IO.StreamReader(request.Stream))
                    using (JsonTextReader reader = new JsonTextReader(streamReader))
                    {
                        JsonSerializer jsonSerializer = JsonSerializer.CreateDefault();
                        JToken token = (JToken)jsonSerializer.Deserialize(reader);
                        DataContextBind.BindJson(dataContext, token);
                    }
                }
            }
        }
    }
```

**Comment by eddyyuen** [comment]
感谢。我是新建了一个JsonResult，在里面做处理了。
