### ISSUE TITLE
如何自定义IResult  谢谢

### ISSUE THREAD

**Issue by guozhigao** [IKende/FastHttpApi#14]
如何自定义IResult  谢谢

**Comment by IKende** [comment]
https://github.com/IKende/FastHttpApi/blob/master/src/IResult.cs
基础实现的IResult都在这个接口文件里，可以参考

**Comment by guozhigao** [comment]
我现在用大神这个做一个服务搭建，供外网调用。我觉得非常OK .不知道大神有什么建议吗？非常感谢

**Comment by IKende** [comment]
其实组件对内外应用都非常不错，也支持静态页面URL重写，现在有些不足的就是没有对多host的支持。

**Comment by guozhigao** [comment]
你说得多host 是指负载吗

**Comment by IKende** [comment]
根据不同请求的域名划分不同的服务

**Comment by guozhigao** [comment]
我觉得这个不影响我现在得构建，我是唯一域名，但是有负载。对外暴露api接口访问都是固定得
