### ISSUE TITLE
如何在Controller的Action处理前获取POST的数据

### ISSUE THREAD

**Issue by eddyyuen** [IKende/FastHttpApi#141]
有个需求是想在Server的HttpRequesting方法统一对POST的数据写日志，但是 Stream的数据读取后就清空了。
所以现在做法是下面这样，能不能有更好的方法，获取数据后不写入？

private void ApiServer_HttpRequesting(object sender, EventHttpRequestArgs e){
                    ...
                    var byteBlock = e.Request.Stream.ReadBytes(e.Request.Length);
                    // TODO 处理 byteBlock.Data
                    e.Request.Stream.Write(byteBlock.Data, 0, byteBlock.Count);
                    e.Request.Stream.Position = 0;
}

**Comment by IKende** [comment]
可以从Stream的buffer链表来获取,stream.FirstBuffer

**Comment by yswenli** [comment]
可以使用 saea相关的组件试试
https://github.com/yswenli/SAEA/tree/master/Src/SAEA.MVCTest/Controllers

**Comment by eddyyuen** [comment]
var buff = e.Request.Stream.FirstBuffer;
已成功读取。
