### ISSUE TITLE
数据绑定bug

### ISSUE THREAD

**Issue by fk364202818** [IKende/FastHttpApi#142]
使用 http://127.0.0.1:6868/GetGISFileInfo1?filename=CKXGL191021~Data~Tile_8~Tile_8.osgb 访问成功，但是使用http://127.0.0.1:6868/GetGISFileInfo1/CKXGL191021~Data~Tile_8~Tile_8.osgb则不行，报“get /GetGISFileInfo1/CKXGL191021~Data~Tile_8~Tile_8.osgb file osgb ext not support”，请问这个怎么解决？

**Comment by eddyyuen** [comment]
有后缀的不行。它会优先获取静态文件
所以这个地址，实际上获取的是 /views/GetGISFileInfo1/CKXGL191021DataTile_8~Tile_8.osgb 这个文件。
解决方法，用参数 或者 不要带后缀【.osgb】

**Comment by eddyyuen** [comment]
还有一种方法就是Controller这样写：
[Get(Route = "{filename}**/**")]
public JsonResult GetGISFileInfo1(string filename)

然后这样访问：
http://127.0.0.1:6868//GetGISFileInfo1/CKXGL191021DataTile_8~Tile_8.osgb**/**

**Comment by fk364202818** [comment]
> 还有一种方法就是Controller这样写：
> [Get(Route = "{filename}/")]
> public JsonResult GetGISFileInfo1(string filename)
> 
> 然后这样访问：
> http://127.0.0.1:6868//GetGISFileInfo1/CKXGL191021DataTile_8~Tile_8.osgb/

谢谢，我尝试一下。但是也有大量请求文件的应用场景，能否从代码上修复这个问题呢？

**Comment by IKende** [comment]
`ext not support`服务没有配置对应的扩展文件输出支持，可以通过
``` csharp
 mServer.AddExts("woff;tff;zip;rar;cs;java;txt;ttf;woff2;svg");
```
来添加或自己在httpconfig.json中添加.

有后缀的会优先访问文件，但也可以通过Url重写来做指向
http://doc.beetlex.io/#2ca7fc0d97334f29a5154d7a063ebe83
不过组件暂定义时要指定后缀名的，所以要针对不同后缀来定义重写。
