### ISSUE TITLE
有办法支持中文路径和中文文件名吗？

### ISSUE THREAD

**Issue by asuradoll** [IKende/FastHttpApi#143]
当静态文件是中文路径或中文文件名时，会提示找不到文件。
访问URL：http://192.168.0.57:7777/中文.txt
提示：/%E4%B8%AD%E6%96%87.txt file not found

这样的提示没有走全局过滤器，应该在更深层被处理掉了，这个有办法解决吗？
因为项目有很多中文静态文件，课程等，用英文目录和英文名的话管理不便

**Comment by IKende** [comment]
中文名测试过是可以的，你看一下文件是不是放在views目录下。也可以把你存在问题的情况做个sample放上来

**Comment by asuradoll** [comment]
> 中文名测试过是可以的，你看一下文件是不是放在views目录下。也可以把你存在问题的情况做个sample放上来

感谢回复，更新到最新版的FastHttpApi框架就解决了。
