### ISSUE TITLE
文件切片上传问题

### ISSUE THREAD

**Issue by ethanChou** [IKende/FastHttpApi#16]
用https://github.com/moxiecode/plupload 做文件切片上传时，服务端会切片解析不全的问题。出现的是有规律的。
服务端代码大概如下
 [Post]
        [MultiDataConvert]
        public object UploadFile(string name, int chunk, int chunks,int offset,string originalname, IHttpContext context)
        {
            //Console.WriteLine($"--------------------- {name} chunk {chunk} chunks {chunks} ");

            if (context.Request.Files.Count==0)
            {
                Console.WriteLine("Files count ===0");
            }
            if (chunk==3)
            {

            }
            foreach (var file in context.Request.Files)
            {
                using (System.IO.Stream stream = System.IO.File.Open(name, System.IO.FileMode.OpenOrCreate, System.IO.FileAccess.ReadWrite))
                {
                    stream.Seek(stream.Length, System.IO.SeekOrigin.Begin);
              
                    byte[] buf = new byte[file.Data.Length];
                    file.Data.Read(buf,0,buf.Length);

                    stream.Write(buf,0,buf.Length);
                    stream.Flush();
                    Console.WriteLine($"{name} chunk {chunk} chunks {chunks} file {file.Data.Length}");
                }
            }

            return $"{DateTime.Now} {name} {string.Join(",", (from fs in context.Request.Files select fs.FileName).ToArray())}";
        }

**Comment by IKende** [comment]
能否把你运行的页面代码提供一下

**Comment by IKende** [comment]
测试暂没发现问题，测试代码如下:
```
[Post]
        [MultiDataConvert]
        public object UploadFile(string name, int chunk, int chunks, int offset, string originalname, IHttpContext context)
        {
            //Console.WriteLine($"--------------------- {name} chunk {chunk} chunks {chunks} ");
            var file = context.Request.Files[0];
            file.Data.Position = 0;
            byte[] data = new byte[file.Data.Length];
            file.Data.Read(data, 0, data.Length);
            if (chunk == 0)
            {
                using (System.IO.Stream stream = System.IO.File.Create("c:\\" + name))
                {
                    stream.Write(data, 0, data.Length);
                    stream.Flush();
                }
            }
            else
            {
                using (System.IO.Stream stream = System.IO.File.Open("c:\\" + name, System.IO.FileMode.Append))
                {
                    stream.Write(data, 0, data.Length);
                    stream.Flush();
                }
            }

            return $"{DateTime.Now} {name} {string.Join(",", (from fs in context.Request.Files select fs.FileName).ToArray())}";
        }
```
Html
```
	runtimes : 'html5,flash,silverlight,html4',
	browse_button : 'pickfiles', // you can pass an id...
	container: document.getElementById('container'), // ... or DOM Element itself
    url: '/UploadFile',
    chunk_size:'200kb',
	flash_swf_url : '/js/Moxie.swf',
	silverlight_xap_url : '/js/Moxie.xap',
	
	filters : {
		max_file_size : '20mb',
		mime_types: [
			{title : "Image files", extensions : "jpg,gif,png"},
			{title : "Zip files", extensions : "zip"}
		]
	},
```
可以把你有问题的项目代码发到:28304340@qq.com
