### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by cqwydz** [IKende/FastHttpApi#17]
System.TypeLoadException: 'Method 'Init' in type 'BeetleX.FastHttpApi.Admin._Admin' from assembly 'BeetleX.FastHttpApi.Admin, Version=0.7.6.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.'

**Comment by IKende** [comment]
新版本的FastHttpApi支持热加载，所以对就Controller的Init方法多添加了一些参数，Nuget上的BeetleX.FastHttpApi.Admin对应的FastHttpApi是旧版本，你只能通过https://github.com/IKende/FastHttpApi/tree/master/Extend/BeetleX.FastHttpApi.Admin
自己编译一个
