### ISSUE TITLE
数据参数定义

### ISSUE THREAD

**Issue by liaozb** [IKende/FastHttpApi#22]
是否支持post这种参数格式     `{
  "Data": {
    "StoryID": 0,
    "Order": 0
  },
  "Uid": "string",
  "Timestamp": 0,
  "Signature": "string",
  "Salt": "string"
}`

**Comment by IKende** [comment]
支持，你定义这样一个结构的类，然后参数名为`body`,这是设计上的约定。
你也可以分开定义,变量名称对应即可如:
```
action (CustomClass Data,string Uid,int Timestamp,string Signature,string Salt)
```

**Comment by liaozb** [comment]
@IKende  好的 谢谢了
