### ISSUE TITLE
请问websocket能用jwtfilter的方式吗？

### ISSUE THREAD

**Issue by zzeric** [IKende/FastHttpApi#38]
blog里介绍的是http get和http post的

**Comment by IKende** [comment]
组件默认的controller/action是支持websocket的jwtfilter，不过需要遵循一些准则。
1）非浏览器在创建websocket连接握手时，必须带上jwt相关信息在`header`上，这样当后面请求的时候会验证握手时候带的`header`
2)如果是浏览器，那你登陆的时候必须以HTTP的方式，然后把jwt信息以cookie的方式保存下来，然后再连接websocket的时候就会自动带上这个 cookie（不排除在些浏览不带）
