### ISSUE TITLE
怎么限定Action是get或者post

### ISSUE THREAD

**Issue by navyblue9** [IKende/FastHttpApi#4]
`[Controller(BaseUrl = "/WxApp/PushMessage")]
    public class WebController : IController
    {
        private BeetleX.FastHttpApi.HttpApiServer mServer;
        [NotAction]
        public void Init(BeetleX.FastHttpApi.HttpApiServer server)
        {
            mServer = server;
        }
        
        public string Get()
        {
            return ("GET:"+DateTime.Now.ToString());
        }

        public string Post()
        {
            return("POST"+DateTime.Now.ToString());
        }
    }`
如上代码,怎么实现 GET请求/WxApp/PushMessage输出GET+时间
POST请求/WxApp/PushMessage输出POST+时间

**Comment by IKende** [comment]
新版已经添加了get,post,put和delete描述
