### ISSUE TITLE
执行 server.SendToWebSocket(data) 内存飙升

### ISSUE THREAD

**Issue by zhusheping** [IKende/FastHttpApi#43]
用FS的websocket，执行了            
mApiServer.SendToWebSocket(data);
这一句后，内存从150M瞬间飙升到550M。

**Comment by IKende** [comment]
websocket默认最大的数据包是1M,你的场景同时向很多连接发送一个大的数据包？

**Comment by zhusheping** [comment]
![image](https://user-images.githubusercontent.com/23443907/58297126-24e05d80-7e09-11e9-9e0a-9daa77dfa6ff.png)

只向一个链接发送了一次很小的数据量。
发送后的瞬间内存就上去了。
![image](https://user-images.githubusercontent.com/23443907/58297225-94564d00-7e09-11e9-9d48-0af6b8f87a10.png)

**Comment by zhusheping** [comment]
![image](https://user-images.githubusercontent.com/23443907/58297340-f4e58a00-7e09-11e9-98ce-5eeaea86e9b3.png)
客户端用的是本地的html。
    <script type="text/javascript">
        //检查浏览器是否支持WebSocket
        if (!window.WebSocket) {
            console.log('您的浏览器不支持WebSocket，请选择其他的浏览器再尝试连接服务器');
        }
        var el = document.getElementById("textarea");
        var wsClient = new WebSocket('ws://localhost:9090');

        wsClient.onopen = function(evt) { 
            console.log("Connection open ..."); 
            wsClient.send("login:1");
            wsClient.send("Hello WebSockets!");
        };
        wsClient.onclose = function (e) {
            el.value += "连接断开！\r\n";
        }
        wsClient.onmessage = function (e) {
            el.value += "接收消息：" + e.data + "\r\n";
        }
        wsClient.onerror = function (e) {
            el.value += "连接失败！原因【" + e.data + "】\r\n";
        }
    </script>

**Comment by IKende** [comment]
@zhusheping 
方便的话把代码打包到发到henryfan@msn.com邮箱,以上代码没发现异常。

**Comment by IKende** [comment]
@zhusheping 
针对你描述的情况修改一下sample的代码，暂没发现你说的情况
https://github.com/IKende/FastHttpApi/tree/master/samples/HttpApiServer.WebSocket

**Comment by IKende** [comment]
@zhusheping 
本地没有core 3.0,用2.2测试没问题
[https://ikende.com/Files/TestFastHttpApi.rar](https://ikende.com/Files/TestFastHttpApi.rar)

**Comment by zhusheping** [comment]
是的，我改成2.2之后，内存就只是从10m升高到25m了。 
------------------
Deep Mind Solutions. We Help .Solutions for Printing Industry 




Name：朱社平

Mob:  +8618993794536 
zhusp@deepmind.cn
Guangzhou, China


 

 




------------------ 原始邮件 ------------------
发件人: "Henry"<notifications@github.com>; 
发送时间: 2019年5月24日(星期五) 中午11:55
收件人: "IKende/FastHttpApi"<FastHttpApi@noreply.github.com>; 
抄送: "阿平"<790978@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [IKende/FastHttpApi] 执行 server.SendToWebSocket(data) 内存飙升 (#43)




@zhusheping
 针对你描述的情况修改一下sample的代码，暂没发现你说的情况
 https://github.com/IKende/FastHttpApi/tree/master/samples/HttpApiServer.WebSocket
