### ISSUE TITLE
DataFrame doesn't collect via GC

### ISSUE THREAD

**Issue by Vladislav93** [IKende/FastHttpApi#44]
Hey! I'm making web socket server with broadcasting. 
I have constant count of connections (for example 500, separate for room by 30 users). One user sends to the server message, server broadcast to another in the same room.
And after a stress test I'm looking up some way to resolve issue: GC doesn't collect DataFrame object. I tried to turn on Server GC but result still the same, DataFrame objects still grows. I tried to make debug field "false"...

**Comment by IKende** [comment]
You can view the DataFrame number of session in Session.Count property. or using DebugDiag tools dump appliation memory ,analysis GC memory.

**Comment by Vladislav93** [comment]
> You can view the DataFrame number of session in Session. Count property. or using DebugDiag tools dump application memory, analysis GC memory.
yeah, I got it: "ConcurrentQueue<object> mSendMessages" is growing up and does not have time to dequeue. Maybe you have some example of broadcasting case?

**Comment by IKende** [comment]
This situation may be when the physical network is disconnected, but does not respond to the socket sending the completed event, causing the message to remain in the queue, and you can release the session.

https://github.com/IKende/FastHttpApi/tree/master/samples/HttpApiServer.SimpleChatRoom
