### ISSUE TITLE
serverGC提示问题

### ISSUE THREAD

**Issue by AlunYjj** [IKende/FastHttpApi#45]
![image](https://user-images.githubusercontent.com/34364607/59158822-fb0a8480-8af2-11e9-8eb0-0b495327bae3.png)
![image](https://user-images.githubusercontent.com/34364607/59158828-0d84be00-8af3-11e9-9434-cbda40ef5ca9.png)
<PropertyGroup>
    <ServerGarbageCollection>true</ServerGarbageCollection>
  </PropertyGroup>
都设置了，但是还是提示[Warring] no serverGC mode,please enable serverGC mode!

**Comment by AlunYjj** [comment]
<PropertyGroup>
    <ServerGarbageCollection>true</ServerGarbageCollection>
  </PropertyGroup> 这个也设置了

**Comment by AlunYjj** [comment]
![image](https://user-images.githubusercontent.com/34364607/59158874-65232980-8af3-11e9-936f-c96883bb130f.png)
这个也设置了

**Comment by IKende** [comment]
设置后你要重新生成，紧紧是编译生成是不会生成运行配置的文件。最直接的办法是修改发布目录 下的`xxx.runtimeconfig.json`文件
```
  "runtimeOptions": {
    "tfm": "netcoreapp2.1",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "2.1.0"
    },
    "configProperties": {
      "System.GC.Server": true
    }
  }
```

**Comment by AlunYjj** [comment]
2019-06-09 22:16:16.4833 AllServer 0001  System.Reflection.Metadata, Version=1.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a load assembly System.Reflection.Metadata.resources, Version=1.4.3.
0, Culture=zh-CN, PublicKeyToken=b03f5f7f11d50a3a error Could not load file or assembly 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.2.4\System.Reflection.Metadata.resources.dll'. 系统找不到指
定的文件。
这边重写了Log的方法，报错信息会弹这个，这个在.netCore是没有的

**Comment by AlunYjj** [comment]
主要是想在Http这边报错，能通知到自己这边用邮件提醒

**Comment by IKende** [comment]
这个不影响组件使用，由于组件捕捉了加载程序集事件，所以会打印出一些程序集无法加载的情况。
