### ISSUE TITLE
是否可以设置不以方法名做路由？

### ISSUE THREAD

**Issue by lvrongwu** [IKende/FastHttpApi#47]
比如如下方法想以 ip:port/medias/10003形式的地址访问 而不是 ip:port/getmedias/10003，再就是{mediaid} 不能写成{media_id}，是否下划线在参数中是不允许使用的
 [Get(Route = "{mediaid}")]
 public object GetMedias(string mediaid)

**Comment by IKende** [comment]
是的暂不支持，这个地方是需要改进一下

**Comment by IKende** [comment]
可以引用新版本`1.5.3.2`
``` csharp
[Get(Route = "medias/{mediaid}")]
public object GetMedias(string mediaid)
```

**Comment by IKende** [comment]
对于返回的内容可以定义Result,后缀名的url会认为是文件请求,http body是有大小限制（需配置）
详细可查看文档
http://ikende.com/doc/

**Comment by lvrongwu** [comment]
请问是否可以在路由上设置多个参数值而不是使用问号
        [Get(Route = "login/{appKey}/{userName}/{password}")]
        [SkipFilter(typeof(GlobalFilter))]
        public object Login(string appKey, string userName, string password)

**Comment by IKende** [comment]
多个参数不支持`/`分隔，因为这是路径字符。
暂不支持只开启ssl.
