### ISSUE TITLE
限定Action是get或者Post提交

### ISSUE THREAD

**Issue by navyblue9** [IKende/FastHttpApi#5]
`[Controller(BaseUrl = "/WxApp/PushMessage")]
    public class WebController : IController
    {
        private BeetleX.FastHttpApi.HttpApiServer mServer;
        [NotAction]
        public void Init(BeetleX.FastHttpApi.HttpApiServer server)
        {
            mServer = server;
        }

        
        public string Get()
        {
            return ("GET:"+DateTime.Now.ToString());
        }

        public string Post()
        {
            return("POST"+DateTime.Now.ToString());
        }
    }`
get 请求 /WxApp/PushMessage 调用get方法

**Comment by IKende** [comment]
组件暂时没有区分GET或POST，内部通过Http的Length来进行处理
BaseUrl 是用于指定基础路径
方法会加上BaseUrl 进行访问

**Comment by IKende** [comment]
组件暂不支持这种方式

**Comment by navyblue9** [comment]
` public string PushMessage(string key,[BodyParameter]string body, IHttpContext context)
        {
            var flag = context.Request.Method == "POST";
            var token = "";
            if (flag)
            {                                                          
                return $"POST请求{key}";
            }
            else
            {                
                return $"GET请求{key}";
            }


        }`


这样可以区分出来了，但是这个body参数没有取到值
能否像 core 下Controller里
` using (Stream stream = Request.Body)
            {
                var bytes = new byte[Request.ContentLength.Value];
                stream.Read(bytes, 0, bytes.Length);
                stream.Dispose();
                var postString = Encoding.UTF8.GetString(bytes);
                
            }`
取值
方法的参数不变

**Comment by navyblue9** [comment]
刚发现已经支持了，谢谢
