### ISSUE TITLE
希望出一个依赖注入的DEMO

### ISSUE THREAD

**Issue by caoxuanyu** [IKende/FastHttpApi#50]

**Comment by nodyang** [comment]
能不能结合autofac

**Comment by IKende** [comment]
http://ikende.com/doc/
帮助文档里有描述

**Comment by caoxuanyu** [comment]
文档中也看过了。照着弄，也没有正常注入进来。希望大神出个Demo

**Comment by IKende** [comment]
https://github.com/IKende/FastHttpApi/tree/master/samples/DependencyInjection
这里有个DI注入扩展sample，需要引用`BeetleX.FastHttpApi.Hosting `
