### ISSUE TITLE
程序部署在centos上以后台运行的方式启动，接口不响应

### ISSUE THREAD

**Issue by lvrongwu** [IKende/FastHttpApi#53]
您好，请问下我程序部署在centos上以后台运行的方式启动（后面加&方式启动的），通过接口访问一直无响应，假死状态，前端运行一直正常。
很少在linux系统上部署过程序，请问下是框架不支持，还是我这边程序开发发布配置的问题？ 谢谢额

**Comment by IKende** [comment]
框架支持在linux下运行，你可以查看相关日志。
在运行目录下有个logs目录下有服务日志

**Comment by nodyang** [comment]
> 请问下我程序部署在centos上以后台运行的方式启动（后面加&方式启动的），通过接口访问
你找supervisor进程管理器 这样的管理去管理。要不然很容易被kill 掉

**Comment by lvrongwu** [comment]
> 框架支持在linux下运行，你可以查看相关日志。
> 在运行目录下有个logs目录下有服务日志

我以你提供的demo （HttpApiServer.HelloWorld）部署在linux下前端运行可以访问，如果添加&方式允许就是一直无响应假死状态
![image](https://user-images.githubusercontent.com/7583820/68015328-e494dd80-fccc-11e9-8195-3e120adcdb31.png)
![image](https://user-images.githubusercontent.com/7583820/68015387-07bf8d00-fccd-11e9-916a-785dd212d7ed.png)
以上在前端运行正常

![image](https://user-images.githubusercontent.com/7583820/68015466-32114a80-fccd-11e9-9cf3-74899b635768.png)
![image](https://user-images.githubusercontent.com/7583820/68015541-553bfa00-fccd-11e9-9fab-ae19f0082153.png)
以上以 &后台运行 网页及接口长时间一直无响应

**Comment by IKende** [comment]
建议使用hosting启动
https://github.com/IKende/FastHttpApi/wiki/Hosting%E5%92%8CDI%E6%B3%A8%E5%85%A5%E6%8E%A7%E5%88%B6%E5%99%A8

**Comment by lvrongwu** [comment]
> 建议使用hosting启动
> https://github.com/IKende/FastHttpApi/wiki/Hosting%E5%92%8CDI%E6%B3%A8%E5%85%A5%E6%8E%A7%E5%88%B6%E5%99%A8

大佬，我参照你给你意见使用hosting启动，但是控制器没有起来，所有接口不可用
![image](https://user-images.githubusercontent.com/7583820/68522596-e3c10480-02e7-11ea-8581-05a192bc9ab4.png)

然后我又恢复到我原来的启动方式，由于更新到了最新版本，现在所有设置的路由跟方法名称不一致的访问请求都不可用
![image](https://user-images.githubusercontent.com/7583820/68522614-1bc84780-02e8-11ea-8c6b-ba163789d919.png)
现在用的链接库的版本
![image](https://user-images.githubusercontent.com/7583820/68522626-3b5f7000-02e8-11ea-9b08-b7f5074cf78f.png)
以上路由跟方法名不一致的都不能通过路由访问，怀疑路由都失效了，是否是升级新版本后哪个配置没有设置

**Comment by IKende** [comment]
是的新版本重新调整了日志，日志里应该会有记录路由定义重写内容
http://doc.ikende.com/#2ca7fc0d97334f29a5154d7a063ebe83

**Comment by lvrongwu** [comment]
> 是的新版本重新调整了日志，日志里应该会有记录路由定义重写内容
> http://doc.ikende.com/#2ca7fc0d97334f29a5154d7a063ebe83

![image](https://user-images.githubusercontent.com/7583820/69138881-7472be00-0afa-11ea-854d-00cadad54a4e.png)
看重新路由没有问题，但是通过路由访问的提示不支持
![image](https://user-images.githubusercontent.com/7583820/69138953-953b1380-0afa-11ea-894b-d769959cfd02.png)
头痛
