### ISSUE TITLE
EmailFormater正则表达式有问题

### ISSUE THREAD

**Issue by hugeng1979** [IKende/FastHttpApi#56]
判断  abc@abc.com 正常，
判断 abc@abc.com.cn 有问题，不匹配。

**Comment by hugeng1979** [comment]
原正则：
^([A-Z|a-z|0-9](\.|_){0,1})+[A-Z|a-z|0-9]\@([A-Z|a-z|0-9])+((\.){0,1}[A-Z|a-z|0-9]){2}\.[a-z]{2,3}$
修改为：
^([A-Z|a-z|0-9](\.|_){0,1})+[A-Z|a-z|0-9]\@([A-Z|a-z|0-9])+((\.){0,1}[A-Z|a-z|0-9]){3}\.[a-z]{2,3}$

将2改为3

**Comment by IKende** [comment]
谢谢，组件可能暂没这么快更新版本，可以自己扩展修改
```
    public class MyEmailFormater : Regex
    {
        public EmailFormater() : base(@"^([A-Z|a-z|0-9](\.|_){0,1})+[A-Z|a-z|0-9]\@([A-Z|a-z|0-9])+((\.){0,1}[A-Z|a-z|0-9]){3}\.[a-z]{2,3}$") { }
        public override string GetResultMessage(string parameter)
        {
            return $"The '{parameter}' parameter value not a email data format";
        }
    }
```

**Comment by hugeng1979** [comment]
nuget上最新是1.5.4.2， github源码最新上1.5.3.2。
所以我没敢直接改源码编译来使用。按你说的，自己增加一个扩展类来实现吧。等你更新。加油。
