### ISSUE TITLE
请问,如何获取client IP address?

### ISSUE THREAD

**Issue by senioi** [IKende/FastHttpApi#59]
context.HttpContext.Request.RemoteIPAddress 目前只发现这个可用,.但是这个返回的是:
::ffff:127.0.0.1:7345
目前已知获取方法:

>  string clientIP = context.HttpContext.Request.Host.Split(':')[0];

有没有更高效的获取方式?

**Comment by IKende** [comment]
如果没经过代理的情况下可以`Request.Session.RemoteEndPoint`,如果经过代理，那就要看代码没有设置相关头信息了

**Comment by IKende** [comment]
`Request.RemoteIPAddress `是先获取Header["X-Real-IP"],如果没有也是从`Request.Session.RemoteEndPoint`转，因为默认启用了ipv6,所以会多了些信息。
