### ISSUE TITLE
netcore 2.0 静态资源乱码

### ISSUE THREAD

**Issue by senioi** [IKende/FastHttpApi#60]
HttpApiServer.UploadFile 切换到netcore 2.0,就乱码了.新手不懂,多谢赐教.
![image](https://user-images.githubusercontent.com/42415346/64994730-03e9ce00-d90c-11e9-81f4-8afa02a272d2.png)
请问这个是不兼容2.0引起的吗?

**Comment by IKende** [comment]
组件基于netcore 2.1，建议用2.1或更高版本
