### ISSUE TITLE
非http协议可能会导致DDOS宕机

### ISSUE THREAD

**Issue by senioi** [IKende/FastHttpApi#61]
非协议内的数据,fasthttpapi会抛出异常,不会断开连接.
如果一直保持连接,发送任意字节,fasthttpapi会一直抛出异常导致cpu增加.
建立tcp连接后不停发送任意字节,fasthttpapi会cpu100%
测试:telnet 127.0.0.1 9090 按住回车
![image](https://user-images.githubusercontent.com/42415346/65012652-b476c280-d94a-11e9-9a14-3d807575eca4.png)
.

**Comment by senioi** [comment]
如果没开启ssl协议,发送ssl hello 包,也不会断开,一直占着连接.

**Comment by IKende** [comment]
1.5.6.6版本已优化

**Comment by senioi** [comment]
@IKende 可能还是有点问题.
![image](https://user-images.githubusercontent.com/42415346/65366117-43892080-dc52-11e9-9bc9-950e87da5a5e.png)
用telnet 测试,打了几个aaa(可能是中文"啊啊啊")
打了几个回车.
抛出这几条错误后,http服务断开彻底挂了.

**Comment by senioi** [comment]
貌似不是挂了..是IP被禁止了
