### ISSUE TITLE
请求中文乱码

### ISSUE THREAD

**Issue by usnail** [IKende/FastHttpApi#62]
**该问题是怎么引起的？**
使用POST提交表单数据，表单中含有中文

**重现步骤**
使用POST提交表单数据，表单中含有中文，请求编码使用**GBK**

**报错信息**
控制器和DataContent获取到的中文乱码，转码数据会丢失。
通过断点调试发现:
FormUrlDataConvertAttribute 

 string data = request.Stream.ReadString(request.Length);

socker中的流编码是UTF-8

**Comment by IKende** [comment]
是的，组件Stream的相关字符操作是utf-8,需要自己写一个FormUrlDataConvertAttribute转换器，具体如下
```
    public class GBKFormUrlDataConvertAttribute : DataConvertAttribute
    {
        public override void Execute(IDataContext dataContext, HttpRequest request)
        {
            if (request.Length > 0)
            {
                var bytes = new Byte[request.Length];
                request.Stream.Read(bytes,0,bytes.Length);
                string data = Encoding.GetEncoding("GBK").GetString(bytes);
                DataContextBind.BindFormUrl(dataContext, data);
            }
        }
    }
```
然后把这个转换器标记在控制器或方法上。

**Comment by usnail** [comment]
> 是的，组件Stream的相关字符操作是utf-8,需要自己写一个FormUrlDataConvertAttribute转换器，具体如下
> 
> ```
>     public class GBKFormUrlDataConvertAttribute : DataConvertAttribute
>     {
>         public override void Execute(IDataContext dataContext, HttpRequest request)
>         {
>             if (request.Length > 0)
>             {
>                 var bytes = new Byte[request.Length];
>                 request.Stream.Read(bytes,0,bytes.Length);
>                 string data = Encoding.GetEncoding("GBK").GetString(bytes);
>                 DataContextBind.BindFormUrl(dataContext, data);
>             }
>         }
>     }
> ```
> 
> 然后把这个转换器标记在控制器或方法上。

好的 谢谢
