### ISSUE TITLE
请问如何在一个controller中得到mApiServer

### ISSUE THREAD

**Issue by hugeng1979** [IKende/FastHttpApi#63]
主要目的是想用
mApiServer.log方法写日志。

之前我用FileLogWriter来写日志，但是这个日志文件和 BEETLEX_HTTP_SERVER 不是同一个日志文件。
当要查看controller记录的异常时，需要去看2个文件的相关内容。
因此，想将日志也写到 BEETLEX_HTTP_SERVER 里。

**Comment by hugeng1979** [comment]
这样写，代码会不会恶心了点？
 
public class Global
    {
        public static HttpApiServer ApiServer;
    }

    class Program
    {
        static void Main(string[] args)
        {
            Global.ApiServer = new HttpApiServer();
            Global.ApiServer.Options.Filters.Add(new JandarWebApi.Filters.CatchExceptionAttribute());
            Global.ApiServer.Register(typeof(Program).Assembly);
            //加载管理插件
            Global.ApiServer.Register(typeof(BeetleX.FastHttpApi.Admin._Admin).Assembly);
            Global.ApiServer.Open();
            Console.Write(Global.ApiServer.BaseServer);
            Console.Read();
            
        }

    }

**Comment by IKende** [comment]
可以引用`DI`扩展，然后直接在控制器构造函数中注入https://github.com/IKende/FastHttpApi/wiki/Hosting%E5%92%8CDI%E6%B3%A8%E5%85%A5%E6%8E%A7%E5%88%B6%E5%99%A8,
还有一种直接在方法中定义一个IHttpContext参数

**Comment by hugeng1979** [comment]
谢谢。根据你的提示已经实现了。
为了读取HttpConfig.json,我先写了个方法LoadOptions


        static void Main(string[] args)
        {
            var options = LoadOptions(); //加载参数文件
            options.Filters.Add(new WebApi.Filters.CatchExceptionAttribute());  //增加自定义异常处理
            var builder = new HostBuilder()
                .ConfigureServices((hostContext, services) =>
                {
                    services
                    .AddSingleton<UserService>()
                    .UseBeetlexHttp(o =>
                    {
                        o = options;
                    }, typeof(Program).Assembly, typeof(BeetleX.FastHttpApi.Admin._Admin).Assembly);
                });
            builder.Build().Run();
            

        }

        public static HttpOptions LoadOptions()
        {
            string mConfigFile = "HttpConfig.json";
            string file = Directory.GetCurrentDirectory() + System.IO.Path.DirectorySeparatorChar + mConfigFile;
            if (System.IO.File.Exists(file))
            {
                using (System.IO.StreamReader reader = new StreamReader(mConfigFile, Encoding.UTF8))
                {
                    string json = reader.ReadToEnd();
                    if (string.IsNullOrEmpty(json))
                        return new HttpOptions();
                    Newtonsoft.Json.Linq.JToken toke = (Newtonsoft.Json.Linq.JToken)Newtonsoft.Json.JsonConvert.DeserializeObject(json);
                    if (toke["HttpConfig"] != null && toke["HttpConfig"].Type == JTokenType.Object)
                    {
                        return toke["HttpConfig"].ToObject<HttpOptions>();
                    }
                    return new HttpOptions();
                }
            }
            else
            {
                return new HttpOptions();
            }
        }

**Comment by hugeng1979** [comment]
另外问个题外话。 管理工具集成里的api view，能否显示出注释的方法说明呢？ 类似 swagger
我们就不用想其它方法来实现了。

**Comment by IKende** [comment]
暂没有，可以通过`HttpApiServer.ActionFactory`里可以获取所有api详细信息。
