### ISSUE TITLE
请问BeetleX有下载文件的样本吗?

### ISSUE THREAD

**Issue by senioi** [IKende/FastHttpApi#65]
对不起,刚入C#坑,很多不懂,一直拿BeetleX做学习样本.
如果问题有点奇葩,请见谅.
试了下 new HttpApiClient new HttpClusterApi
貌似都无法实现,返回数据没有流或者byte[],只有obj和string.
而且必须绑定query才能用,如果是伪静态不允许查询参数就没法用了.
**比如:**
> https://steamusercontent-a.akamaihd.net/ugc/780736294753192669/3233D0C9D6BFA88D5F59EBD6471F2D242D8C7101/

请问这类地址怎么操作?

```
    [Controller(BaseUrl = "ugc/780736294753192669/")]
 public interface IDataService
    {
        [Get]
        Task<PipeStream> 3233D0C9D6BFA88D5F59EBD6471F2D242D8C7101();
    }
```

这样操作真实地址变成了:

> https://steamusercontent-a.akamaihd.net/ugc/780736294753192669/3233D0C9D6BFA88D5F59EBD6471F2D242D8C7101

直接404了,请问这类地址,我该如何正确获得流或者byte[]?

**Comment by IKende** [comment]
下载文件类的建议直接用httpclient,这个库的基础设计是针对业务对象API，你这情况需要扩展对应的formater.
https://github.com/IKende/HttpClients/blob/master/src/IBodyFormater.cs
