### ISSUE TITLE
windows下添加服务启动总报错1053

### ISSUE THREAD

**Issue by ktkxc** [IKende/FastHttpApi#67]
请问如何windows服务自动启动？
我这边是发布的release版本，用dotnet 路径/**.dll,在cmd命令里可以正常启动，但是通过sc create 方式添加服务后启动总是报错 1053 服务没有及时响应启动或控制请求，网上找了各种方法，权限等均解决不了，所以请问怎么在windows下以服务自动启动的方式运行？或者其他自动启动的方式运行？
创建服务命令代码如下：
`sc create BeetleXweb binpath= "\"C:\Program Files\dotnet\dotnet.exe\" \"E:\***\bin\Release\netcoreapp2.2\publish\kqnetcorecode.dll\"" type= share start= auto displayname= "BeetleX Serviceweb"`

**Comment by IKende** [comment]
我一般都是加载Hosting然后在docker中运行，在windwos我是通过启动里添加个bat来运行的。

**Comment by ktkxc** [comment]
@IKende 感谢回复，windows的IIS配置访问不了（不知道有没有人能在IIS上搭建成功过），只能用服务形式才不能一直出现cmd窗口（万一不小心关掉窗口就不好了）。
后来就找如何建windows服务了，经过几天的折腾终于在一个偶然的机会找到了用nssm的方式创建服务，现在可以以服务的方式自动启动并看不见窗口（cmd）运行了。
