### ISSUE TITLE
提两个功能需求

### ISSUE THREAD

**Issue by kingflyok** [IKende/FastHttpApi#69]
1、可以全局设置跨域
2、可以支持类似swagger的功能

**Comment by kingflyok** [comment]
再补充一个就是，如果加了全局过滤器之后，管理后台的控制器也会自动加载，这个有办法忽略嘛，或者加个什么忽略列表

**Comment by IKende** [comment]
更新到1.6.8
`Options.CrossDomain`可以设置全局跨域配置,新版本的admin不再受全局filter影响。
`swagger`其实可以自己集成，只需要通过` HttpApiServer.ActionFactory.Handlers`来生成对应的json文件即可

**Comment by chaojicpu** [comment]
> OK 我试试

测试成功了吗？

**Comment by kingflyok** [comment]
最近一直在忙项目，到处飞，还没时间测试
