### ISSUE TITLE
看什么时候方便支持一下IOC等功能

### ISSUE THREAD

**Issue by flyliao** [IKende/FastHttpApi#7]
看什么时候支持这种依赖注入，以前很多项目可能就会无缝切换到FastHttpApi上面来
        /// <summary>
        ///     IoC 初始化
        /// </summary>
        /// <param name="services"></param>
        /// <returns></returns>
        private IServiceProvider InitIoC(IServiceCollection services)
        {
            // 数据库链接字符串
            services.Configure<AppSettings>(Configuration.GetSection("AppSettings"));

            services.AddScoped<IDatabaseContext, MySqlContext>();

            services.AddTransient<IUnitOfWork, UnitOfWork>();
}

**Comment by IKende** [comment]
考虑引入一个 控制器创建事件，用于给应用者在事件中使用IOC组件创建控制器对象
