### ISSUE TITLE
添加LRU缓存和更全面的Url重写机制

### ISSUE THREAD

**Issue by IKende** [IKende/FastHttpApi#70]
加入LRU缓存功能类，Url重写机制支持更完善如支持下规则重写:
`/Orders/{user}/{Suppliers}` to `/Orders?user={user}&Suppliers={Suppliers}`

**Comment by IKende** [comment]
更新至1.6.9

**Comment by imsk** [comment]
怎么加载appsettings.{}.json文件的配置呢？

**Comment by IKende** [comment]
可以自己引入Microsoft.Extensions.Configuration.Json来处理
