### ISSUE TITLE
地址重写不生效或者间接性故障

### ISSUE THREAD

**Issue by fenfei100** [IKende/FastHttpApi#77]
比如说我要将 /page/{name} 转向 /api/page/{name} 我测试过一下规则：
1. 标准格式
	{
		"Url": "/page/{name}/",
		"Rewrite": "/api/page/{name}"
	}
2. 通过request，分析query string来判断操作

	{
		"Url": "/page/{name}/",
		"Rewrite": "/api/page?id={name}"
	}
3. Url 中 page 关键词修改为其他关键词

	{
		"Url": "/info/{name}/",
		"Rewrite": "/api/page/{name}"
	}
4. Url 中 page 关键词修改为其他关键词，再通过request，分析query string来判断操作

	{
		"Url": "/info/{name}/",
		"Rewrite": "/api/page?id={name}"
	}

最后发现只有4的操作成功过，但是这个成功是间歇性的，比如启动十来次程序有那么一两次有效
3号也出现过Rewrite成功，只是Rewrite成功而已，而非执行成功
3偶尔可以将 /info/abc/ 这种地址转换成 /api/page/abc 但是不会在控制 /api/page/{name} 上执行，最终返回的是 404

我想知道的是，是 Rewrite 规则错误了还是我理解错误了，我用的是 1.7.2.2

**Comment by fenfei100** [comment]
刚更新到 1.7.3.6 貌似 1/3 号规则都可以使用了，但是2/4 这种可以Rewrite了，但是不能执行

**Comment by fenfei100** [comment]
目前的解决办法是： 
{
"Url": "/page/{name}/",
"Rewrite": "/api/page"
}

然后在 /api/page 的控制器上判断 context.Data?.Item("name") 才能正常执行

**Comment by IKende** [comment]
多层路径的重写是要新版才支持
对2/4 这种可以Rewrite了，如果不匹配是可以查看404返回的路径看有没重写错误
组件重写后是不会带上?id={name},主要原因是{name}已经注入到DataContext中了，会自动绑定到action的参数中

**Comment by fenfei100** [comment]
我已经使用了最新的版本，1/3可以了，2/4 我的理解是应该重写到 /api/page  上，然后自动附加 name 到 Data 列表中。而实际是已经将 name 输出到 Url 上了，所以会出现这个问题。

另外我尝试了 /abc/{name}/index.html 这种 /abc/{name}/{id}.html 都没有重写，直接输出的是 404

**Comment by IKende** [comment]
你需要的可能是这种
 /abc/{name}/{id}.html 这种 /abc/{name}?id={id}

**Comment by fenfei100** [comment]
是不是对于 .html 这种由后缀的路径重写路径后只是不是直接去找对应的静态文件了，而没有再去通过控制器来处理，比如说：/abc/{name}/{id}.html 这种 /abc/{name}?id={id} 转向后它去找静态目录下是否由/abc/{name} 这个文件，而不是去找 /abc/{name} 这个控制器了

**Comment by fenfei100** [comment]
刚测试，感觉我的理解是对的。另外如果 /abc/{name}/{id}.html 写再 json 文件最后面，这个规则不生效，需要在后面加一个其他不带后缀的规则才行
