### ISSUE TITLE
Controller基类如何实现

### ISSUE THREAD

**Issue by ulyanovsk** [IKende/FastHttpApi#8]
Controller基类如何实现
如：
方法加载前打开数据库，
方法结束后关闭数据库

**Comment by IKende** [comment]
这个功能要用Filter,https://github.com/IKende/FastHttpApi/tree/master/samples/HttpApiServer.Filters

**Comment by IKende** [comment]
还可以控制器实现，IController接口的Init方法
```
        [NotAction]
        public void Init(HttpApiServer server)
        {
            this.Server = server;
            this.HandleFactory = Server.ActionFactory;
        }
```
还能通过继承`ParameterBinder`进行参数注入，如果你想每个action都重新打开和关闭就用Filter比较适合

**Comment by ulyanovsk** [comment]
好的，我试试，多谢
