### ISSUE TITLE
装配对象的问题

### ISSUE THREAD

**Issue by zhusheping** [IKende/FastHttpApi#80]
![image](https://user-images.githubusercontent.com/23443907/68832708-9d571580-06ec-11ea-8528-615a9f963a41.png)
但实际上数据是传递过来的。
![image](https://user-images.githubusercontent.com/23443907/68832745-b95ab700-06ec-11ea-945f-a3647938ecd1.png)
只是没有装配成功。

**Comment by IKende** [comment]
如果参数是绑定整个Json body,参数名必须为'body'

**Comment by zhusheping** [comment]
ok,解决了谢谢。
