### ISSUE TITLE
using the new pipelines library

### ISSUE THREAD

**Issue by GCat** [IKende/FastHttpApi#85]
what's your thoughts on using the new pipeline for FastHttpAPI ?
[https://devblogs.microsoft.com/dotnet/system-io-pipelines-high-performance-io-in-net/](https://devblogs.microsoft.com/dotnet/system-io-pipelines-high-performance-io-in-net/)

**Comment by IKende** [comment]
The new pipeline on FastHttpAPI is not considered for the time,[beetlex](https://github.com/IKende/BeetleX) has pipestream to manage the network buffers
