### ISSUE TITLE
HttpRequest.Stream只能读取一次？

### ISSUE THREAD

**Issue by laiguorong** [IKende/FastHttpApi#91]
现需求是要在过滤器FilterAttribute.Executing实现校验签名，发现在数据转换之后，Stream就没有数据了，无法再次读取报文，能否增加原报文内容的属性字段？或有其他解决方案。

**Comment by IKende** [comment]
你可以把stream读出来检验后根据自己处理设置到Context.Data中即可,大概始下:
``` csharp
 public override bool Executing(ActionContext context)
        {
            context.HttpContext.Data.SetValue("myData",data);
            return base.Executing(context);
        }
```

**Comment by laiguorong** [comment]
这样的话，需要写个自定义JsonDataConvert，把stream读出来的内容保存到Context.Data，一来在FilterAttribute.Executing可以读取来校验签名，二来Action也可以映射到body参数

**Comment by IKende** [comment]
是的也可以通过`DataConvert`来做
