### ISSUE TITLE
请求头的Key默认转小写？

### ISSUE THREAD

**Issue by laiguorong** [IKende/FastHttpApi#92]
请问请求头的Key默认转小写的？而匹配的时候却没有区分大小写，请问有什么解决方案能保持大小写敏感，或保持请求的时候头的Key的大小不变？

**Comment by laiguorong** [comment]
发现运行后首次在postman上发起请求，header的key是客户端所请求的，之后不管在postman还是前端发起请求都是客户端的；而如果首次在前端发起请求的话，header的key就变成小写，之后不管哪里都是小写；

前端是用fetch组件，一直在用的，发起请求到netcore的wepapi是没有问题的；

**Comment by IKende** [comment]
组件对header的key设计暂时是这样，这个头的key第一次创建是怎样就是固定了，后面的请求头即使有变化也是依据第一次创建的来

**Comment by laiguorong** [comment]
主要是前端发起的header会变小写，postman却不会，或者我能在什么地方提前初始化header的？

**Comment by IKende** [comment]
可以调用
`HeaderTypeFactory.Find(name)`
