### ISSUE TITLE
关于以注入模式运行会导致的问题

### ISSUE THREAD

**Issue by gwhzh21** [IKende/FastHttpApi#97]
1>以注入模式运行的时候，
BeetleX.FastHttpApi.Hosting 这个我没有找到最新的代码。但是老代码，我看了一下。
第80行是这么写的
 if (mSettingHandler.Assemblies != null)
                mHttpServer.Register(mSettingHandler.Assemblies);
这里是没有问题，但是在
ActionHandlerFactory的public void Register(params Assembly[] assemblies)的时候
ControllerAttribute ca = type.GetCustomAttribute<ControllerAttribute>(false);
                    if (ca != null)
                    {
                        try
                        {
                            EventControllerInstanceArgs e = new EventControllerInstanceArgs();
                            e.Type = type;
                            OnControllerInstance(e);
                            if (e.Controller == null)
                            {
                              ###   **Register(Server.Options, type, Activator.CreateInstance(type), ca.BaseUrl, Server, ca, null);**
这里会有一个问题，会导致非单例的对象在这里被迫被初始化了一次，注入同时在此发生了，比如说像一些注入的资源在此被创建。
                            }
                            else
                            {
                                Register(Server.Options, type, e.Controller, ca.BaseUrl, Server, ca, null);
                            }
                        }
                        catch (Exception e_)
                        {
                            if (Server.EnableLog(EventArgs.LogType.Error))
                            {
                                string msg = $"{type} controller register error {e_.Message} {e_.StackTrace}";
                                Server.Log(EventArgs.LogType.Error, msg);
                            }
                        }
                    }

前面的那个问题，我使用建议，新建了一个类，大约是这样写的，
public class Class1
    {
        public System.Data.IDbConnection connection
        {
            get
            { 
                return new SqlConnection(@"");
            }
        }
}
在其它类注入这个类，解决问题

**Comment by gwhzh21** [comment]
补充下，虽然我知道在哪有点不好，但是我也不知道怎么改它。

**Comment by IKende** [comment]
你可以把`HttpApiServer`注入到控器中或通过参数`IHttpContext`，只要用引`BeetleX.FastHttpApi.Hosting`空间即即可以
``` csharp
Server.ServiceProvider()
```
即可获取ＤＩ容器实例，手动获取相关注入对象。

**Comment by gwhzh21** [comment]
好的。回头一下。
