### ISSUE TITLE
使用Hosting和DI注入控制器后，全局异常怎么才能生效？

### ISSUE THREAD

**Issue by hugeng1979** [IKende/FastHttpApi#99]
` static void Main(string[] args)
        {
            var options = LoadOptions();
            options.Filters.Add(new WebApi.Filters.CatchException());
            var builder = new HostBuilder()
                .ConfigureServices((hostContext, services) =>
                {
                    services
                    .AddSingleton<UserService>()
                    .UseBeetlexHttp(o =>
                    {
                        o = options;
                    }, typeof(Program).Assembly, typeof(BeetleX.FastHttpApi.Admin._Admin).Assembly);
                });
            builder.Build().Run();           

        }`
目前，Controller运行正常，但是全局异常不生效。当在某个Controller中 throw new exception("dddd”）时，
我在CatchException里设置断点，发现程序没有走到这里来就返回了。
最终前台获得的是http500错误。

**Comment by IKende** [comment]
把`CatchException`的代码出来看一下

**Comment by IKende** [comment]
https://github.com/IKende/BeetleX-Samples/tree/master/Web.ExecptionFilter
可以查看这示例

**Comment by hugeng1979** [comment]
/// <summary>
    /// 全局异常处理
    /// </summary>
    public class CatchException : FilterAttribute
    {
        public override void Executed(ActionContext context)
        {
            base.Executed(context);   //我在这行设置断点，调试时controller那边主动抛出异常后，程序不会走到此断点
            if (context.Exception != null)
            {
                context.Result = new JsonResult(new ActionResult(-9999, "出现异常:" + context.Exception.Message) { StackTrace=context.Exception.StackTrace});
                context.Exception = null;
            }
        }
    }

**Comment by IKende** [comment]
不能这样设置option,因为那个o并不是ref参

**Comment by hugeng1979** [comment]
经过测试。
我原来的代码是：
 class Program
    {
        static void Main(string[] args)
        {
            var options = LoadOptions();
            var builder = new HostBuilder()
                .ConfigureServices((hostContext, services) =>
                {
                    services
                    .AddSingleton<UserService>()
                    .UseBeetlexHttp(o =>
                    {
                        o = options;
                        o.Filters.Add(new JandarWebApi.Filters.CatchException());
                    }, typeof(Program).Assembly, typeof(BeetleX.FastHttpApi.Admin._Admin).Assembly);
                });
            builder.Build().Run();
            

        }

        public static HttpOptions LoadOptions()
        {
            string mConfigFile = "HttpConfig.json";
            string file = Directory.GetCurrentDirectory() + System.IO.Path.DirectorySeparatorChar + mConfigFile;
            if (System.IO.File.Exists(file))
            {
                using (System.IO.StreamReader reader = new StreamReader(mConfigFile, Encoding.UTF8))
                {
                    string json = reader.ReadToEnd();
                    if (string.IsNullOrEmpty(json))
                        return new HttpOptions();
                    Newtonsoft.Json.Linq.JToken toke = (Newtonsoft.Json.Linq.JToken)Newtonsoft.Json.JsonConvert.DeserializeObject(json);
                    if (toke["HttpConfig"] != null && toke["HttpConfig"].Type == JTokenType.Object)
                    {
                        return toke["HttpConfig"].ToObject<HttpOptions>();
                    }
                    return new HttpOptions();
                }
            }
            else
            {
                return new HttpOptions();
            }
        }
    }

option是先通过方法LoadOptions 从配置文件HttpConfig.json中加载。 
以上的方法，全局异常过滤器不能正常使用。

改为以下的代码，全局异常过滤器就正常使用了。
  class Program
    {
        static void Main(string[] args)
        {
            var builder = new HostBuilder()
                .ConfigureServices((hostContext, services) =>
                {
                    services
                    .AddSingleton<UserService>()
                    .UseBeetlexHttp(o =>
                    {
                        //o = options;
                        o.LogToConsole = true;
                        o.ManageApiEnabled = false;
                        o.Port = 8001;
                        o.SetDebug();
                        o.LogLevel = BeetleX.EventArgs.LogType.Warring;
                        o.Filters.Add(new JandarWebApi.Filters.CatchException());
                    }, typeof(Program).Assembly, typeof(BeetleX.FastHttpApi.Admin._Admin).Assembly);
                });
            builder.Build().Run();
            

        }
}
先废弃了LoadOptions方法，之后全局异常过滤器能正常使用。
你有什么好的建议来加载配置文件吗？

**Comment by IKende** [comment]
``` csharp
o = options;
```
o参数不是`ref`，所以无法代替原来的变量值的。

**Comment by hugeng1979** [comment]
最终做了如下修改，全局过滤器正常了。
var builder = new HostBuilder()
                .ConfigureServices((hostContext, services) =>
                {
                    services
                    .AddSingleton<UserService>()
                    .UseBeetlexHttp(o =>
                    {
                        LoadOptions(o);
                        o.Filters.Add(new JandarWebApi.Filters.CatchException());
                    }, typeof(Program).Assembly, typeof(BeetleX.FastHttpApi.Admin._Admin).Assembly);
                });
            builder.Build().Run();
上面的代码，改在UseBeetlexHttp方法里使用LoadOptions(o);

 public static void LoadOptions(HttpOptions options)
        {
            string mConfigFile = "HttpConfig.json";
            string file = Directory.GetCurrentDirectory() + System.IO.Path.DirectorySeparatorChar + mConfigFile;
            if (System.IO.File.Exists(file))
            {
                using (System.IO.StreamReader reader = new StreamReader(mConfigFile, Encoding.UTF8))
                {
                    string json = reader.ReadToEnd();
                    if (string.IsNullOrEmpty(json))
                        return;
                    Newtonsoft.Json.Linq.JToken toke = (Newtonsoft.Json.Linq.JToken)Newtonsoft.Json.JsonConvert.DeserializeObject(json);
                    if (toke["HttpConfig"] != null && toke["HttpConfig"].Type == JTokenType.Object)
                    {
                        Type type = options.GetType(); //获取类型
                        foreach (JProperty jp in toke["HttpConfig"])
                        {
                            System.Reflection.PropertyInfo propertyInfo = type.GetProperty(jp.Name); //获取指定名称的属性
                            propertyInfo.SetValue(options, Convert.ChangeType
                   (jp.Value, propertyInfo.PropertyType.UnderlyingSystemType), null);
                        }
                    }
                }
            }
        }
在LoadOptions方法中，将参数options，针对httpconfig的内容一项一项赋值。
